spring:
  h2:
    console:
      enable: true
  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Dev_Local
    username: root
    password: 1016
  jpa:
    properties:
      hibernate:
        default_schema: dev_local
  security:
    ignored: -"*.bundle.*"

# Email Services
  mail:
    host: smtp.gmail.com
    port: 587
    username: pidgeontheatres@gmail.com
    password: ekgbrgbuazvwdulp
    properties:
      mail:
        stmp:
          auth: true
          starttls:
            enable: true
