spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Dev_Local
    username: root
    password: 1016
  jpa:
    properties:
      hibernate:
        default_schema: dev_local
  security:
    ignored: /**
  mail:
    host: smtp.gmail.com
    port: 587
    username: pigeon.theatres@gmail.com
    password: pigeon098
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true